### ISSUE TITLE
bug: Create a new project variant for vtmn-badge

### ISSUE THREAD

**Issue by choqchoq-dkt** [Decathlon/vitamin-web#1251]
Hello I am using the CSS class "vtmn-badge"
I am trying to create a new variant CSS class to be able to use it anywhere in the same spirit of this class "vtmn-badge_variant--selected". 

My class 
```
@layer components {
    .vtmn-badge_variant--selected {
        background-color: var(--vtmn-color_brand-digital-dark-2);
        color: var(--vtmn-semantic-color_content-primary-reversed);
        box-shadow: none;
    }
}
```

However when I used it.

```
<span className="vtmn-badge vtmn-badge_variant--selected">
              10
</span>
```

The "vtmn-badge" is overriding the "vtmn-badge_variant--selected" properties.
In the Chrome style console
<img width="687" alt="image" src="https://user-images.githubusercontent.com/90247150/187203522-e3f01855-4f82-4245-89d7-f4246b4ae666.png">

I don't know i a configuration is necessary ? Could you help me with this issue ? 
Thanks.

**Comment by Tlahey** [comment]
Hello @choqchoq-dkt , if you want to create another variant for a component, you new class must have a better ponderation.

For example : 

```css
@layer components {
    .my-component {
      .vtmn-badge_variant--selected {
          background-color: var(--vtmn-color_brand-digital-dark-2);
          color: var(--vtmn-semantic-color_content-primary-reversed);
          box-shadow: none;
      }
  }
}
```

```html 
<div className="my-component">
  <span className="vtmn-badge vtmn-badge_variant--selected">
                10
  </span>
</div>
```

Should do the stuff :)
