### ISSUE TITLE
bug:  wrong vertical position of `.vtmn-popover`

### ISSUE THREAD

**Issue by beatrizsmerino-decathlon** [Decathlon/vitamin-web#1259]
# Describe the bug

The vitamine styles of the `.vtmn-popover` component are failing.
The vertical position is made with `%`, so depending on the height it has, in this case, by the amount of text, it moves from the information icon.

![image](https://user-images.githubusercontent.com/108340378/191034997-88e643f2-bb2b-46f9-8dbe-e394c9595038.png)
![image](https://user-images.githubusercontent.com/108340378/191035028-76ea7fe6-9b46-4680-9119-459cfdf5291c.png)
![image](https://user-images.githubusercontent.com/108340378/191035056-11063181-5f03-4fde-bd73-a01394dbf02b.png)

# Steps to reproduce

    1. After add some products to the cart, go to the [Shipping page](http://localhost:3000/es/checkout/shipping) and continue  with the purchase.
    2. Click on the icon `vtmx-information-line` of the `shipping-drawer-popover`
    3. You will see that the tooltip information is displayed and it is superimposed on the icon you have just clicked on.
    
![image](https://user-images.githubusercontent.com/108340378/191038556-0845ac8d-fa31-4287-a226-a6ff7987e762.png)

# Expected behavior

Shifting the `.vtmn-popover` down the `0.6rem` that measures the height of the arrow corrects the problem.

![image](https://user-images.githubusercontent.com/108340378/191035152-f62889c8-7710-4d18-a1a8-b8a574989570.png)
![image](https://user-images.githubusercontent.com/108340378/191038864-80e55fe0-b1b5-45ef-a8da-f16c4a4259a0.png)

So to fix it, change this...

```less
.vtmn-popover[data-position='bottom-left'] > [role='tooltip'] {
    transform: translate(-90%, 120%);
}
.vtmn-popover[data-position^='bottom'] > [role='tooltip'] {
    bottom:  100%;
    left: 50%;
    transform: translate(-50%, 100%);
}
```

...to this:

```less
.vtmn-popover[data-position='bottom-left'] > [role='tooltip'] {
    transform: translate(-90%, 100%);
}
.vtmn-popover[data-position^='bottom'] > [role='tooltip'] {
    bottom:  -0.6em;
    left: 50%;
    transform: translate(-50%, 100%);
}
```

By inspecting with the browser console you can test how these styles are affected
