### ISSUE TITLE
bug: customize the browser scrollbar of `.vtmn-overflow-y-scroll`

### ISSUE THREAD

**Issue by beatrizsmerino-decathlon** [Decathlon/vitamin-web#1263]
# Describe the bug
This error is related to this [task](https://github.com/dktunited/front-ux-es/pull/3219), where it has been corrected by overwriting vitamine styles. But the best solution would be to have it integrated in vitamine.

![image](https://user-images.githubusercontent.com/108340378/191921861-7a164f7c-011a-4d9f-aef5-f6712304c40d.png)

Using a Mac, and in Chrome and Safari the vertical scrollbar is only shown when the mouse is over the content and actively scrolling.
OSx hides scrollbars when not in use to make it look more _"elegant"_, but at the same time causes the user to not be able to see if a content has a scroll function or not.

The `.vtmn-overflow-y-scroll` class applies the browser's native scroll to it and that's not enough to make it always display.

![image](https://user-images.githubusercontent.com/108340378/191920105-23c55a32-a52f-40e8-baab-577f27b9cbbb.png)

# Steps to reproduce
1. Open the menu and click on: `Hombres/Ropa deportiva/Pantalones`.
2. And look at the filters on the left side of the page.

![image](https://user-images.githubusercontent.com/108340378/191920562-c68bc6de-b51f-4784-8feb-82cd72f613de.png)

# Expected behavior

To solve the problem on `Mac` with `Chrome` and `Safari` you can apply css styles, to create the scrollbar horizontal and vertical ourselves.

```less
.vtmn-overflow-y-scroll::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 7px;
}

.vtmn-overflow-y-scroll::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: rgba(0,0,0,.5);
  -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}
```

```less
.vtmn-overflow-x-scroll::-webkit-scrollbar {
  -webkit-appearance: none;
  height: 7px;
}

.vtmn-overflow-x-scroll::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: rgba(0,0,0,.5);
  -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}
```
But this does not work in `Firefox`.

There is another way to do it and have it always look the same in all browsers but it depends on the user knowing about it and activating it himself (something quite improbable):

For fix it you could customize it from `Mac` in:
`System Preferences / General / Show scrollbars: Always.`
![image](https://user-images.githubusercontent.com/108340378/191937888-b3b06526-f71a-4783-8d4d-4eee29692092.png)

Here is a demo in [Code Pen](https://codepen.io/beatrizsmerino/pen/abGLWjJ?editors=1100) for check it in `Firefox` activating it in `System Preferences`:

Before             |  After
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/108340378/191939024-b162deaf-581b-4d2b-bb50-6d74a41291fe.png) | ![image](https://user-images.githubusercontent.com/108340378/191937979-5c00a283-44fa-4725-9853-ce091be9ceba.png)

In `Chrome` and `Safari` the styles override the settings set in `System Preferences`
Before             |  After
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/108340378/191940428-f3301a97-7f22-4fd3-892e-43d3c8c6e333.png) | ![image](https://user-images.githubusercontent.com/108340378/191938191-b2b3e59a-dac8-4f14-ba20-8dee6b9750f6.png)

On `Firefox` the `scrollbar-color` property only works if you have `Show scroll bars: Always` checked in `General System Preferences`.

# Browsers affected
Choose your browser(s):
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
