### ISSUE TITLE
refactor: line-height shouldn't wear unit

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#29]
# Bug Report

`line-height` cascades down and shouldn't wear unit

**Current behavior**

```css
element {
  font-size: 2rem;
  line-height: 3rem;
}
````
It implies that any children of `element` without explicit `line-height` definition will have a 3rem line-height whatever its font-size may be.

**Expected behavior**

`line-height` should be a multiplicator of font-size. 
```css
element {
  font-size: 2rem;
  line-height: 1.5;
}
````
That way `element` children will have a consistent `line-height` whatever `element` font-size value or unit is.

**Related code**

in /packages/css/src/design-tokens/typography.css

![image](https://user-images.githubusercontent.com/22882255/103233909-91550400-493e-11eb-96e8-c1520a75d85f.png)
