### ISSUE TITLE
bug(@vtmn/css): there are TailwindCSS negative margin classes are returning positive values

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#577]
# Bug Report

**Bug report**

Negative margin tailwind classes output positive values

**Current behavior**

Using negative margin classes (`vtmn--mt-1`, `vtmn--mx-3`, ...) output the same values that their positive counterparts (`vtmn-mt-1`, `vtmn-mx-3`, ...) : 

```css
.vtmn-mx-1 {
  margin-left: var(--vtmn-spacing_1);
  margin-right: var(--vtmn-spacing_1);
}

.vtmn--mx-1 {
  margin-left: var(--vtmn-spacing_1);
  margin-right: var(--vtmn-spacing_1);
}
```

**Expected behavior**

negative margin classes should return their opposite

**Steps to reproduce**

This is visible in the `index-base.css` file

**Related code**

We can either  use explicit custom prop refering to explicit value...
```css
:root {
  ---vtmn-spacing_1: -3rem;
}

div {
  margin-left: var(---vtmn-spacing_1);
}
```

...use explicit custom prop referring to calc-ed value...
```css
:root {
  ---vtmn-spacing_1: calc(var(--vtmn-spacing_1) * -1);
}

div {
  margin-left: var(---vtmn-spacing_1);
}
```

...or use positive value and calc it
```css
:root {
  --vtmn-spacing_1: 3rem;
}

div {
  margin-left: calc(var(--vtmn-spacing_1) * -1);
}
```
