### ISSUE TITLE
bug(preset): font-regular class has two definitions

### ISSUE THREAD

**Issue by bastienterrier** [Decathlon/vitamin-web#749]
After importing `@vtmn/css-tailwind-preset` I got two different definitions for the class helper `font-normal` as below:
```css
.font-normal {
  font-family: Roboto, system-ui, -apple-system, sans-serif;
}

.font-normal {
  font-weight: 400;
}
```

It's due to `fontFamily` theme in preset
```css
  fontFamily: {
      normal: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
      condensed: [
        'Roboto Condensed',
        'system-ui',
        '-apple-system',
        'sans-serif',
      ],
      display: ['Roboto Condensed', 'system-ui', '-apple-system', 'sans-serif'],
      body: ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
    },
```

I think the `fontFamily > normal` should be rename to `regular` to avoid collision between `font-family` and `font-weight`.

Best regards
